### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Cobertos** [datejer/vercel-badge#1]
I noticed this project has no License for the code. Can you consider adding one?

**Comment by datejer** [comment]
Ah... you're right, I totally forgot about it!

**Comment by datejer** [comment]
Added in https://github.com/datejer/vercel-badge/pull/2 👍

**Comment by Cobertos** [comment]
Thanks so much!

I ended up using a lot of this in https://github.com/Cobertos/fitbit-sleebies . This is such a nice repository for making 1 off badges :3
